const data = {
  products: [
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 700,
      brand: "Nike",
      rating: 4.5,
      numReviews: 9,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 700,
      brand: "Nike",
      rating: 4.5,
      numReviews: 9,
      countInStock: 20,
      description: "Guru's shirt",
    },
    {
      name: "Green Shirt",
      slug: "green-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 700,
      brand: "Nike",
      rating: 4.5,
      numReviews: 9,
      countInStock: 20,
      description: "Nice shirt",
    },
    {
      name: "Blazer",
      slug: "blazer",
      category: "Shirts",
      image: "/images/blazer.jpg",
      price: 700,
      brand: "Nike",
      rating: 4.5,
      numReviews: 9,
      countInStock: 20,
      description: "Nice shirt",
    },
  ],
};

export default data;